# This file is part of BurnMan - a thermoelastic
# and thermodynamic toolkit for the Earth and Planetary Sciences
# Copyright (C) 2012 - 2026 by the BurnMan team, released under the GNU
# GPL v2 or later.

"""
ig51G25
^^^^^^^

HPx-eos solutions using endmembers from
dataset HPx_ds636.

Contains the following solutions:
* liq_G25w
* fl_G25
* ol_H18
* g_W24
* spl_T21
* fsp_H22
* cpx_W24
* opx_W24
* ilm_W24
* bi_G25
* mu_W14
* amp_G16
* ep_H11
* cd_G25

Oxygen buffers: fmq, nno.

Green et al. (2025), doi:10.1093/petrology/egae079.
Source: tc-ig51G25.txt, G25 release uploaded 2025-05-07.
https://hpxeosandthermocalc.org/wp-content/uploads/2025/05/tc-thermoinput-igg25-h18corr-2024-12-21.zip

The values in this document are all in S.I. units,
unlike those in the original THERMOCALC file.

This file is autogenerated using hpx_eos_to_burnman.py
"""

import numpy as np
from numpy import array, nan
from . import HPx_ds636
from ..classes.mineral import Mineral
from ..classes.solution import Solution
from ..classes.solutionmodel import SymmetricRegularSolution
from ..classes.solutionmodel import AsymmetricRegularSolution
from ..classes.combinedmineral import CombinedMineral

geik_nood = Mineral(
    {
        "name": "geik",
        "formula": {"Mg": 1.0, "Ti": 1.0, "O": 3.0},
        "equation_of_state": "hp_tmt",
        "H_0": -1568656.0,
        "S_0": 74.6,
        "V_0": 3.086e-05,
        "Cp": [136.1, 0.001656, -2533000.0, -283.9],
        "n": 5.0,
        "molar_mass": 0.1201702,
        "a_0": 2.15e-05,
        "K_0": 170000000000.0,
        "Kprime_0": 8.3,
        "Kdprime_0": -4.882352941176471e-11,
        "T_0": 298.15,
        "F_0": 0.0,
        "P_0": 100000.0,
        "G_0": nan,
        "Gprime_0": nan,
        "T_einstein": 497.94007490636704,
    }
)

herc_nood = Mineral(
    {
        "name": "herc",
        "formula": {"Fe": 1.0, "Al": 2.0, "O": 4.0},
        "equation_of_state": "hp_tmt",
        "H_0": -1949047.0,
        "S_0": 113.9,
        "V_0": 4.075000000000001e-05,
        "Cp": [184.9, 0.01417, -3674800.0, -404.0],
        "n": 7.0,
        "molar_mass": 0.1738056,
        "a_0": 2.06e-05,
        "K_0": 192200000000.0,
        "Kprime_0": 4.04,
        "Kdprime_0": -2.1019771071800207e-11,
        "T_0": 298.15,
        "F_0": 0.0,
        "P_0": 100000.0,
        "G_0": nan,
        "Gprime_0": nan,
        "T_einstein": 468.310479305573,
    }
)

ilm_nood = Mineral(
    {
        "name": "ilm",
        "formula": {"Fe": 1.0, "Ti": 1.0, "O": 3.0},
        "equation_of_state": "hp_tmt",
        "H_0": -1232276.0,
        "S_0": 107.5,
        "V_0": 3.169e-05,
        "Cp": [125.3, 0.009938, -2458100.0, -25.9],
        "n": 5.0,
        "molar_mass": 0.15171020000000002,
        "a_0": 2.4e-05,
        "K_0": 170000000000.0,
        "Kprime_0": 8.3,
        "Kdprime_0": -4.882352941176471e-11,
        "T_0": 298.15,
        "F_0": 0.0,
        "P_0": 100000.0,
        "G_0": nan,
        "Gprime_0": nan,
        "T_einstein": 380.67287043664993,
    }
)

sp_nood = Mineral(
    {
        "name": "sp",
        "formula": {"Mg": 1.0, "Al": 2.0, "O": 4.0},
        "equation_of_state": "hp_tmt",
        "H_0": -2299712.0,
        "S_0": 80.63,
        "V_0": 3.978e-05,
        "Cp": [200.5, 0.006252, -2996400.0, -888.4],
        "n": 7.0,
        "molar_mass": 0.1422656,
        "a_0": 1.93e-05,
        "K_0": 192200000000.0,
        "Kprime_0": 4.04,
        "Kdprime_0": -2.1019771071800207e-11,
        "T_0": 298.15,
        "F_0": 0.0,
        "P_0": 100000.0,
        "G_0": nan,
        "Gprime_0": nan,
        "T_einstein": 592.252008591202,
    }
)


q4L = CombinedMineral(
    [HPx_ds636.qL()],
    [4.0],
    [np.float64(1570.0), np.float64(-0.0), np.float64(-3.1000000000000005e-07)],
    "q4L",
)
slL = CombinedMineral(
    [HPx_ds636.silL()],
    [1.0],
    [np.float64(7070.0), np.float64(-0.0), np.float64(-3.3400000000000006e-06)],
    "slL",
)
wo1L = CombinedMineral(
    [HPx_ds636.woL()],
    [1.0],
    [np.float64(650.0), np.float64(-0.0), np.float64(-1.3e-06)],
    "wo1L",
)
fo2L = CombinedMineral(
    [HPx_ds636.foL()],
    [2.0],
    [np.float64(7740.0), np.float64(-0.0), np.float64(-1.56e-06)],
    "fo2L",
)
fa2L = CombinedMineral(
    [HPx_ds636.faL()],
    [2.0],
    [np.float64(13850.0), np.float64(-0.0), np.float64(-5.4e-07)],
    "fa2L",
)
jdL = CombinedMineral(
    [HPx_ds636.abL(), HPx_ds636.qL()],
    [1.0, -1.0],
    [np.float64(11310.0), np.float64(-0.0), np.float64(-9.200000000000001e-07)],
    "jdL",
)
hmL = CombinedMineral(
    [HPx_ds636.hemL()],
    [0.5],
    [np.float64(2930.0), np.float64(-0.0), np.float64(-4.1000000000000004e-07)],
    "hmL",
)
ekL = CombinedMineral(
    [HPx_ds636.eskL()],
    [0.5],
    [np.float64(25020.0), np.float64(-0.0), np.float64(2.4400000000000004e-06)],
    "ekL",
)
tiL = CombinedMineral(
    [HPx_ds636.ruL()],
    [1.0],
    [np.float64(-6240.0), np.float64(-0.0), np.float64(-2.35e-06)],
    "tiL",
)
kjL = CombinedMineral(
    [HPx_ds636.kspL(), HPx_ds636.qL()],
    [1.0, -1.0],
    [np.float64(11690.0), np.float64(-0.0), np.float64(-2.02e-06)],
    "kjL",
)
ctL = CombinedMineral(
    [HPx_ds636.woL(), HPx_ds636.silL(), HPx_ds636.qL()],
    [1.0, 1.0, -1.0],
    [np.float64(-106160.0), np.float64(-55.0), np.float64(5.2e-07)],
    "ctL",
)
h2o1L = CombinedMineral(
    [HPx_ds636.h2oL()],
    [1.0],
    [np.float64(3590.0), np.float64(4.1000000000000005), np.float64(6.5e-09)],
    "h2o1L",
)
qfL = CombinedMineral(
    [HPx_ds636.qL()],
    [4.0],
    [np.float64(2650.0), np.float64(-0.0), np.float64(-7.1e-07)],
    "qfL",
)
slfL = CombinedMineral(
    [HPx_ds636.silL()],
    [1.0],
    [np.float64(6290.0), np.float64(-0.0), np.float64(-3.86e-06)],
    "slfL",
)
wofL = CombinedMineral(
    [HPx_ds636.woL()],
    [1.0],
    [np.float64(-200.0), np.float64(-0.0), np.float64(-1.6100000000000003e-06)],
    "wofL",
)
fofL = CombinedMineral(
    [HPx_ds636.foL()],
    [2.0],
    [np.float64(7560.0), np.float64(-0.0), np.float64(-1.25e-06)],
    "fofL",
)
fafL = CombinedMineral(
    [HPx_ds636.faL()],
    [2.0],
    [np.float64(15540.0), np.float64(-0.0), np.float64(-1.03e-06)],
    "fafL",
)
jdfL = CombinedMineral(
    [HPx_ds636.abL(), HPx_ds636.qL()],
    [1.0, -1.0],
    [np.float64(10590.0), np.float64(-0.0), np.float64(-3.85e-06)],
    "jdfL",
)
hmfL = CombinedMineral(
    [HPx_ds636.hemL()],
    [0.5],
    [np.float64(4050.0), np.float64(-0.0), np.float64(-7.7e-07)],
    "hmfL",
)
ekfL = CombinedMineral(
    [HPx_ds636.eskL()],
    [0.5],
    [np.float64(24750.0), np.float64(-0.0), np.float64(2.4500000000000003e-06)],
    "ekfL",
)
tifL = CombinedMineral(
    [HPx_ds636.ruL()],
    [1.0],
    [np.float64(5690.0), np.float64(-0.0), np.float64(-4.84e-06)],
    "tifL",
)
kjfL = CombinedMineral(
    [HPx_ds636.kspL(), HPx_ds636.qL()],
    [1.0, -1.0],
    [np.float64(12210.0), np.float64(-0.0), np.float64(-3.45e-06)],
    "kjfL",
)
cfm = CombinedMineral(
    [HPx_ds636.fa(), HPx_ds636.fo()],
    [0.5, 0.5],
    [np.float64(0.0), np.float64(-0.0), np.float64(0.0)],
    "cfm",
)
tig = CombinedMineral(
    [HPx_ds636.py(), HPx_ds636.per(), HPx_ds636.ru(), HPx_ds636.cor()],
    [1.0, 0.5, 0.5, -0.5],
    [np.float64(42300.0), np.float64(17.3), np.float64(0.0)],
    "tig",
)
nsp = CombinedMineral(
    [sp_nood], [1.0], [np.float64(0.0), np.float64(0.0), np.float64(0.0)], "nsp"
)
isp = CombinedMineral(
    [sp_nood], [1.0], [np.float64(23500.0), np.float64(5.76303), np.float64(0.0)], "isp"
)
nhc = CombinedMineral(
    [herc_nood], [1.0], [np.float64(0.0), np.float64(0.0), np.float64(0.0)], "nhc"
)
ihc = CombinedMineral(
    [herc_nood],
    [1.0],
    [np.float64(23600.0), np.float64(5.76303), np.float64(0.0)],
    "ihc",
)
nmt = CombinedMineral(
    [HPx_ds636.mt()],
    [1.0],
    [np.float64(0.0), np.float64(-5.76303), np.float64(0.0)],
    "nmt",
)
imt = CombinedMineral(
    [HPx_ds636.mt()],
    [1.0],
    [np.float64(300.0), np.float64(-0.0), np.float64(0.0)],
    "imt",
)
cfs = CombinedMineral(
    [HPx_ds636.fs()],
    [1.0],
    [np.float64(2100.0), np.float64(2.0), np.float64(4.5000000000000003e-07)],
    "cfs",
)
crdi = CombinedMineral(
    [HPx_ds636.cats(), HPx_ds636.kos(), HPx_ds636.jd()],
    [1.0, 1.0, -1.0],
    [np.float64(4850.0), np.float64(-0.0), np.float64(0.0)],
    "crdi",
)
cess = CombinedMineral(
    [HPx_ds636.cats(), HPx_ds636.acm(), HPx_ds636.jd()],
    [1.0, 1.0, -1.0],
    [np.float64(-3460.0), np.float64(-0.0), np.float64(0.0)],
    "cess",
)
cbuf = CombinedMineral(
    [
        HPx_ds636.cats(),
        HPx_ds636.per(),
        HPx_ds636.ru(),
        HPx_ds636.cor(),
    ],
    [1.0, 0.5, 0.5, -0.5],
    [np.float64(-20890.0), np.float64(1.2), np.float64(2.4800000000000004e-06)],
    "cbuf",
)
cen = CombinedMineral(
    [HPx_ds636.en()],
    [1.0],
    [np.float64(3500.0), np.float64(2.0), np.float64(4.800000000000001e-07)],
    "cen",
)
cfm_cpx_W24 = CombinedMineral(
    [HPx_ds636.en(), HPx_ds636.fs()],
    [0.5, 0.5],
    [np.float64(-1600.0), np.float64(2.0), np.float64(4.6500000000000005e-07)],
    "cfm",
)
kjd = CombinedMineral(
    [HPx_ds636.jd(), HPx_ds636.abh(), HPx_ds636.san()],
    [1.0, -1.0, 1.0],
    [np.float64(10820.0), np.float64(-0.0), np.float64(6e-06)],
    "kjd",
)
fm = CombinedMineral(
    [HPx_ds636.en(), HPx_ds636.fs()],
    [0.5, 0.5],
    [np.float64(-6600.0), np.float64(-0.0), np.float64(0.0)],
    "fm",
)
odi = CombinedMineral(
    [HPx_ds636.di()],
    [1.0],
    [np.float64(2800.0), np.float64(-0.0), np.float64(5.0000000000000004e-08)],
    "odi",
)
cren = CombinedMineral(
    [
        HPx_ds636.en(),
        HPx_ds636.cats(),
        HPx_ds636.kos(),
        HPx_ds636.jd(),
        HPx_ds636.di(),
    ],
    [1.0, 1.0, 1.0, -1.0, -1.0],
    [np.float64(-6000.0), np.float64(-0.0), np.float64(1.4000000000000001e-06)],
    "cren",
)
obuf = CombinedMineral(
    [
        HPx_ds636.mgts(),
        HPx_ds636.per(),
        HPx_ds636.ru(),
        HPx_ds636.cor(),
    ],
    [1.0, 0.5, 0.5, -0.5],
    [np.float64(-3910.0), np.float64(5.1000000000000005), np.float64(3.7e-06)],
    "obuf",
)
mess = CombinedMineral(
    [HPx_ds636.mgts(), HPx_ds636.acm(), HPx_ds636.jd()],
    [1.0, 1.0, -1.0],
    [np.float64(3000.0), np.float64(-0.0), np.float64(0.0)],
    "mess",
)
ojd = CombinedMineral(
    [HPx_ds636.jd()],
    [1.0],
    [np.float64(18200.0), np.float64(-0.0), np.float64(0.0)],
    "ojd",
)
oilm = CombinedMineral(
    [ilm_nood], [1.0], [np.float64(0.0), np.float64(0.0), np.float64(0.0)], "oilm"
)
dilm = CombinedMineral(
    [ilm_nood],
    [1.0],
    [np.float64(7050.0), np.float64(5.763146321643979), np.float64(1.3e-06)],
    "dilm",
)
ogk = CombinedMineral(
    [geik_nood], [1.0], [np.float64(0.0), np.float64(0.0), np.float64(0.0)], "ogk"
)
dgk = CombinedMineral(
    [geik_nood],
    [1.0],
    [np.float64(8310.0), np.float64(5.763146321643979), np.float64(0.0)],
    "dgk",
)
annm = CombinedMineral(
    [HPx_ds636.ann()],
    [1.0],
    [np.float64(-3000.0), np.float64(-0.0), np.float64(0.0)],
    "annm",
)
obi = CombinedMineral(
    [HPx_ds636.ann(), HPx_ds636.phl()],
    [0.3333333333333333, 0.6666666666666666],
    [np.float64(-6000.0), np.float64(-0.0), np.float64(0.0)],
    "obi",
)
est = CombinedMineral(
    [HPx_ds636.east()],
    [1.0],
    [np.float64(2200.0), np.float64(-0.0), np.float64(0.0)],
    "est",
)
tbi = CombinedMineral(
    [HPx_ds636.br(), HPx_ds636.phl(), HPx_ds636.ru()],
    [-1.0, 1.0, 1.0],
    [np.float64(55000.0), np.float64(-0.0), np.float64(0.0)],
    "tbi",
)
fbi = CombinedMineral(
    [HPx_ds636.east(), HPx_ds636.acm(), HPx_ds636.jd()],
    [1.0, 1.0, -1.0],
    [np.float64(-7200.0), np.float64(-0.0), np.float64(0.0)],
    "fbi",
)
mat = CombinedMineral(
    [HPx_ds636.ma()],
    [1.0],
    [np.float64(5000.0), np.float64(-0.0), np.float64(0.0)],
    "mat",
)
fmu = CombinedMineral(
    [HPx_ds636.andr(), HPx_ds636.gr(), HPx_ds636.mu()],
    [0.5, -0.5, 1.0],
    [np.float64(25000.0), np.float64(-0.0), np.float64(0.0)],
    "fmu",
)
tsm = CombinedMineral(
    [HPx_ds636.ts()],
    [1.0],
    [np.float64(10000.0), np.float64(-0.0), np.float64(0.0)],
    "tsm",
)
prgm = CombinedMineral(
    [HPx_ds636.parg()],
    [1.0],
    [np.float64(-10000.0), np.float64(-0.0), np.float64(0.0)],
    "prgm",
)
glm = CombinedMineral(
    [HPx_ds636.gl()],
    [1.0],
    [np.float64(-3000.0), np.float64(-0.0), np.float64(0.0)],
    "glm",
)
grnm = CombinedMineral(
    [HPx_ds636.grun()],
    [1.0],
    [np.float64(-3000.0), np.float64(-0.0), np.float64(0.0)],
    "grnm",
)
a = CombinedMineral(
    [HPx_ds636.cumm(), HPx_ds636.grun()],
    [0.42857142857142855, 0.5714285714285714],
    [np.float64(-11200.0), np.float64(-0.0), np.float64(0.0)],
    "a",
)
b = CombinedMineral(
    [HPx_ds636.cumm(), HPx_ds636.grun()],
    [0.2857142857142857, 0.7142857142857143],
    [np.float64(-13800.0), np.float64(-0.0), np.float64(0.0)],
    "b",
)
mrb = CombinedMineral(
    [HPx_ds636.gl(), HPx_ds636.gr(), HPx_ds636.andr()],
    [1.0, -1.0, 1.0],
    [np.float64(0.0), np.float64(-0.0), np.float64(0.0)],
    "mrb",
)
kprg = CombinedMineral(
    [HPx_ds636.mu(), HPx_ds636.pa(), HPx_ds636.parg()],
    [1.0, -1.0, 1.0],
    [np.float64(-7060.0), np.float64(-20.0), np.float64(0.0)],
    "kprg",
)
tts = CombinedMineral(
    [HPx_ds636.dsp(), HPx_ds636.ru(), HPx_ds636.ts()],
    [-2.0, 2.0, 1.0],
    [np.float64(95000.0), np.float64(-0.0), np.float64(0.0)],
    "tts",
)
fmq = CombinedMineral(
    [HPx_ds636.fa(), HPx_ds636.q(), HPx_ds636.mt()],
    [-3.0, 3.0, 2.0],
    [np.float64(0.0), np.float64(-0.0), np.float64(0.0)],
    "fmq",
)
nno = CombinedMineral(
    [HPx_ds636.NiO(), HPx_ds636.Ni()],
    [2.0, -2.0],
    [np.float64(0.0), np.float64(-0.0), np.float64(0.0)],
    "nno",
)


class liq_G25w(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a liq_G25w solution object.
        Contains the following endmembers with associated site occupancies:
        * [q4L, "[Pq][]0[Xv]2"]
        * [slL, "[Alm][Psl][Xv]2"]
        * [wo1L, "[Cam][Pwo][Xv]2"]
        * [fo2L, "[Pol][Mgm]4[Xv]2"]
        * [fa2L, "[Pol][Fem]4[Xv]2"]
        * [jdL, "[Pjd][]0[Xv]2"]
        * [hmL, "[Phm][]0[Xv]2"]
        * [ekL, "[Pek][]0[Xv]2"]
        * [tiL, "[Pti][]0[Xv]2"]
        * [kjL, "[Pkj][]0[Xv]2"]
        * [ctL, "[Pct][]0[Xv]2"]
        * [h2o1L, "[]0[]0[Xh]2"]

        This is implemented as an asymmetric solution.
        """
        self.name = "liq_G25w"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [q4L, "[Pq][]0[Xv]2"],
                [slL, "[Alm][Psl][Xv]2"],
                [wo1L, "[Cam][Pwo][Xv]2"],
                [fo2L, "[Pol][Mgm]4[Xv]2"],
                [fa2L, "[Pol][Fem]4[Xv]2"],
                [jdL, "[Pjd][]0[Xv]2"],
                [hmL, "[Phm][]0[Xv]2"],
                [ekL, "[Pek][]0[Xv]2"],
                [tiL, "[Pti][]0[Xv]2"],
                [kjL, "[Pkj][]0[Xv]2"],
                [ctL, "[Pct][]0[Xv]2"],
                [h2o1L, "[]0[]0[Xh]2"],
            ],
            alphas=[
                100.0,
                120.0,
                140.0,
                240.0,
                100.0,
                120.0,
                100.0,
                100.0,
                100.0,
                100.0,
                100.0,
                65.0,
            ],
            energy_interaction=[
                [
                    9200.0,
                    -10300.0,
                    -47600.0,
                    -13100.0,
                    -15500.0,
                    20000.0,
                    0.0,
                    24100.0,
                    -20100.0,
                    -14200.0,
                    18700.0,
                ],
                [
                    -28500.0,
                    1200.0,
                    2500.0,
                    18800.0,
                    -5000.0,
                    0.0,
                    16200.0,
                    6900.0,
                    3700.0,
                    24300.0,
                ],
                [25900.0, 13900.0, 100.0, 0.0, 0.0, 17900.0, -500.0, 9600.0, 53200.0],
                [17900.0, 100.0, 0.0, 0.0, 9000.0, 3800.0, -7600.0, 21000.0],
                [8300.0, -30000.0, 0.0, -4100.0, 9400.0, -6100.0, 20900.0],
                [9800.0, 0.0, 15400.0, -4700.0, 6800.0, -10100.0],
                [0.0, 0.0, 8900.0, 0.0, 57400.0],
                [0.0, 0.0, 0.0, 60000.0],
                [9600.0, 0.0, 50000.0],
                [-5400.0, 2000.0],
                [8900.0],
            ],
            volume_interaction=[
                [
                    -8.000000000000001e-07,
                    0.0,
                    -4.31e-05,
                    -5.300000000000001e-06,
                    -1.1e-06,
                    0.0,
                    0.0,
                    0.0,
                    -5.000000000000001e-07,
                    3.0000000000000004e-07,
                    -7.100000000000001e-06,
                ],
                [
                    8.3e-06,
                    1.0000000000000002e-06,
                    0.0,
                    4.0000000000000003e-07,
                    0.0,
                    0.0,
                    -4.0000000000000003e-07,
                    1.0000000000000002e-06,
                    0.0,
                    -9.4e-06,
                ],
                [
                    7.000000000000001e-07,
                    0.0,
                    -3.0000000000000004e-07,
                    0.0,
                    0.0,
                    0.0,
                    1.0000000000000002e-06,
                    -4.0000000000000003e-07,
                    -1.1000000000000001e-05,
                ],
                [
                    3.0000000000000004e-07,
                    7.000000000000001e-07,
                    0.0,
                    0.0,
                    0.0,
                    7.000000000000001e-07,
                    0.0,
                    -1.67e-05,
                ],
                [
                    -4.0000000000000003e-07,
                    0.0,
                    0.0,
                    0.0,
                    1.0000000000000002e-06,
                    0.0,
                    -1.6000000000000003e-05,
                ],
                [
                    1.0000000000000001e-07,
                    0.0,
                    1.4000000000000001e-06,
                    1.0000000000000002e-06,
                    0.0,
                    -6.000000000000001e-07,
                ],
                [0.0, 0.0, 1.0000000000000002e-06, 0.0, -6.600000000000001e-06],
                [0.0, 0.0, 0.0, -6.600000000000001e-06],
                [4.0000000000000003e-07, 0.0, -2.0000000000000003e-06],
                [0.0, 6.000000000000001e-07],
                [-3.0000000000000004e-07],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class fl_G25(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a fl_G25 solution object.
        Contains the following endmembers with associated site occupancies:
        * [qfL, "[Pq1/2Fac1/2]2"]
        * [slfL, "[Psl1/2Fac1/2]2"]
        * [wofL, "[Pwo1/2Fac1/2]2"]
        * [fofL, "[Pfo1/2Fac1/2]2"]
        * [fafL, "[Pfa1/2Fac1/2]2"]
        * [jdfL, "[Pjd1/2Fac1/2]2"]
        * [hmfL, "[Phm1/2Fac1/2]2"]
        * [ekfL, "[Pek1/2Fac1/2]2"]
        * [tifL, "[Pti1/2Fac1/2]2"]
        * [kjfL, "[Pkj1/2Fac1/2]2"]
        * [HPx_ds636.H2O(), "[Phtwoo]2"]

        This is implemented as a symmetric solution.
        """
        self.name = "fl_G25"
        self.solution_model = SymmetricRegularSolution(
            endmembers=[
                [qfL, "[Pq1/2Fac1/2]2"],
                [slfL, "[Psl1/2Fac1/2]2"],
                [wofL, "[Pwo1/2Fac1/2]2"],
                [fofL, "[Pfo1/2Fac1/2]2"],
                [fafL, "[Pfa1/2Fac1/2]2"],
                [jdfL, "[Pjd1/2Fac1/2]2"],
                [hmfL, "[Phm1/2Fac1/2]2"],
                [ekfL, "[Pek1/2Fac1/2]2"],
                [tifL, "[Pti1/2Fac1/2]2"],
                [kjfL, "[Pkj1/2Fac1/2]2"],
                [HPx_ds636.H2O(), "[Phtwoo]2"],
            ],
            energy_interaction=[
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 71500.0],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 55400.0],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 83700.0],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 82900.0],
                [0.0, 0.0, 0.0, 0.0, 0.0, 77700.0],
                [0.0, 0.0, 0.0, 0.0, 46100.0],
                [0.0, 0.0, 0.0, 73000.0],
                [0.0, 0.0, 73000.0],
                [0.0, 75900.0],
                [49600.0],
            ],
            volume_interaction=[
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -8.900000000000001e-06],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -9.100000000000001e-06],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -6.1e-06],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.2600000000000001e-05],
                [0.0, 0.0, 0.0, 0.0, 0.0, -1.41e-05],
                [0.0, 0.0, 0.0, 0.0, -8.3e-06],
                [0.0, 0.0, 0.0, -6.600000000000001e-06],
                [0.0, 0.0, -6.600000000000001e-06],
                [0.0, -6.600000000000001e-06],
                [-1.3100000000000002e-05],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class ol_H18(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a ol_H18 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.mont(), "[Mgmone][Camtwo]"]
        * [HPx_ds636.fa(), "[Femone][Femtwo]"]
        * [HPx_ds636.fo(), "[Mgmone][Mgmtwo]"]
        * [cfm, "[Mgmone][Femtwo]"]

        This is implemented as a symmetric solution.
        """
        self.name = "ol_H18"
        self.solution_model = SymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.mont(), "[Mgmone][Camtwo]"],
                [HPx_ds636.fa(), "[Femone][Femtwo]"],
                [HPx_ds636.fo(), "[Mgmone][Mgmtwo]"],
                [cfm, "[Mgmone][Femtwo]"],
            ],
            energy_interaction=[
                [24000.0, 38000.0, 24000.0],
                [9000.0, 4500.0],
                [4500.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class g_W24(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a g_W24 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.py(), "[Mgmone]3[Almtwo]2"]
        * [HPx_ds636.alm(), "[Femone]3[Almtwo]2"]
        * [HPx_ds636.gr(), "[Camone]3[Almtwo]2"]
        * [HPx_ds636.andr(), "[Camone]3[Fethreemtwo]2"]
        * [HPx_ds636.knor(), "[Mgmone]3[Crmtwo]2"]
        * [tig, "[Mgmone]3[Almtwo1/2Mgmtwo1/4Timtwo1/4]2"]

        This is implemented as an asymmetric solution.
        """
        self.name = "g_W24"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.py(), "[Mgmone]3[Almtwo]2"],
                [HPx_ds636.alm(), "[Femone]3[Almtwo]2"],
                [HPx_ds636.gr(), "[Camone]3[Almtwo]2"],
                [HPx_ds636.andr(), "[Camone]3[Fethreemtwo]2"],
                [HPx_ds636.knor(), "[Mgmone]3[Crmtwo]2"],
                [tig, "[Mgmone]3[Almtwo1/2Mgmtwo1/4Timtwo1/4]2"],
            ],
            alphas=[1.0, 1.0, 2.5, 2.5, 1.0, 1.0],
            energy_interaction=[
                [4000.0, 45400.0, 107000.0, 2000.0, 1000.0],
                [17000.0, 65000.0, 8200.0, 0.0],
                [2000.0, 5000.0, -3000.0],
                [63000.0, -1000.0],
                [0.0],
            ],
            entropy_interaction=[
                [-0.0, 10.0, 10.0, -0.0, -0.0],
                [10.0, 10.0, -0.0, -0.0],
                [-0.0, 10.0, -0.0],
                [10.0, -0.0],
                [-0.0],
            ],
            volume_interaction=[
                [1.0000000000000002e-06, 4.0000000000000003e-07, -3.6e-07, 0.0, 0.0],
                [1.0000000000000002e-06, 3.9e-07, 1.0000000000000001e-07, 0.0],
                [0.0, 1.8000000000000001e-06, 0.0],
                [1.0000000000000002e-06, 0.0],
                [0.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class spl_T21(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a spl_T21 solution object.
        Contains the following endmembers with associated site occupancies:
        * [nsp, "[Mgt][Alm]"]
        * [isp, "[Alt][Mgm1/2Alm1/2]"]
        * [nhc, "[Fet][Alm]"]
        * [ihc, "[Alt][Fem1/2Alm1/2]"]
        * [nmt, "[Fet][Fethreem]"]
        * [imt, "[Fethreet][Fem1/2Fethreem1/2]"]
        * [HPx_ds636.picr(), "[Mgt][Crm]"]
        * [HPx_ds636.usp(), "[Fet][Fem1/2Tim1/2]"]

        This is implemented as an asymmetric solution.
        """
        self.name = "spl_T21"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [nsp, "[Mgt][Alm]"],
                [isp, "[Alt][Mgm1/2Alm1/2]"],
                [nhc, "[Fet][Alm]"],
                [ihc, "[Alt][Fem1/2Alm1/2]"],
                [nmt, "[Fet][Fethreem]"],
                [imt, "[Fethreet][Fem1/2Fethreem1/2]"],
                [HPx_ds636.picr(), "[Mgt][Crm]"],
                [HPx_ds636.usp(), "[Fet][Fem1/2Tim1/2]"],
            ],
            alphas=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9],
            energy_interaction=[
                [-6700.0, 3600.0, -9800.0, 43200.0, 49500.0, -38400.0, 40000.0],
                [2700.0, -3500.0, 36800.0, 20700.0, -21600.0, 38200.0],
                [-6000.0, 17500.0, 51600.0, -53800.0, 25700.0],
                [-4100.0, 10000.0, -38800.0, 21000.0],
                [18100.0, 12100.0, 5200.0],
                [-8700.0, 21500.0],
                [15000.0],
            ],
            volume_interaction=[
                [0.0, 0.0, 0.0, 0.0, 0.0, -8.000000000000001e-07, 0.0],
                [0.0, 0.0, 0.0, 0.0, -8.000000000000001e-07, 0.0],
                [0.0, 0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0],
                [0.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class fsp_H22(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a fsp_H22 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.ab(), "[Naa][Altb1/4Sitb3/4]"]
        * [HPx_ds636.an(), "[Caa][Altb1/2Sitb1/2]"]
        * [HPx_ds636.san(), "[Ka][Altb1/4Sitb3/4]"]

        This is implemented as an asymmetric solution.
        """
        self.name = "fsp_H22"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.ab(), "[Naa][Altb1/4Sitb3/4]"],
                [HPx_ds636.an(), "[Caa][Altb1/2Sitb1/2]"],
                [HPx_ds636.san(), "[Ka][Altb1/4Sitb3/4]"],
            ],
            alphas=[0.674, 0.55, 1.0],
            energy_interaction=[[14600.0, 24100.0], [48500.0]],
            entropy_interaction=[[9.350000000000001, 9.57], [-0.0]],
            volume_interaction=[
                [-4.0000000000000003e-07, 3.3800000000000007e-06],
                [-1.3e-06],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class cpx_W24(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a cpx_W24 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.di(), "[Mgmone][Camtwo][Sit]1/2"]
        * [cfs, "[Femone][Femtwo][Sit]1/2"]
        * [HPx_ds636.cats(), "[Almone][Camtwo][Sit1/2Alt1/2]1/2"]
        * [crdi, "[Crmone][Camtwo][Sit1/2Alt1/2]1/2"]
        * [cess, "[Fethreemone][Camtwo][Sit1/2Alt1/2]1/2"]
        * [cbuf, "[Mgmone1/2Timone1/2][Camtwo][Sit1/2Alt1/2]1/2"]
        * [HPx_ds636.jd(), "[Almone][Namtwo][Sit]1/2"]
        * [cen, "[Mgmone][Mgmtwo][Sit]1/2"]
        * [cfm_cpx_W24, "[Mgmone][Femtwo][Sit]1/2"]
        * [kjd, "[Almone][Kmtwo][Sit]1/2"]

        This is implemented as an asymmetric solution.
        """
        self.name = "cpx_W24"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.di(), "[Mgmone][Camtwo][Sit]1/2"],
                [cfs, "[Femone][Femtwo][Sit]1/2"],
                [HPx_ds636.cats(), "[Almone][Camtwo][Sit1/2Alt1/2]1/2"],
                [crdi, "[Crmone][Camtwo][Sit1/2Alt1/2]1/2"],
                [cess, "[Fethreemone][Camtwo][Sit1/2Alt1/2]1/2"],
                [cbuf, "[Mgmone1/2Timone1/2][Camtwo][Sit1/2Alt1/2]1/2"],
                [HPx_ds636.jd(), "[Almone][Namtwo][Sit]1/2"],
                [cen, "[Mgmone][Mgmtwo][Sit]1/2"],
                [cfm_cpx_W24, "[Mgmone][Femtwo][Sit]1/2"],
                [kjd, "[Almone][Kmtwo][Sit]1/2"],
            ],
            alphas=[1.2, 1.0, 1.9, 1.9, 1.9, 1.9, 1.2, 1.0, 1.0, 1.2],
            energy_interaction=[
                [
                    25800.0,
                    13000.0,
                    8000.0,
                    8000.0,
                    8000.0,
                    26000.0,
                    29800.0,
                    20600.0,
                    26000.0,
                ],
                [25000.0, 38300.0, 43300.0, 24000.0, 24000.0, 2300.0, 3500.0, 24000.0],
                [2000.0, 2000.0, 6000.0, 6000.0, 45200.0, 27000.0, 6000.0],
                [2000.0, 6000.0, 3000.0, 52300.0, 40300.0, 3000.0],
                [6000.0, 3000.0, 57300.0, 45300.0, 3000.0],
                [16000.0, 24000.0, 22000.0, 16000.0],
                [40000.0, 26000.0, 28000.0],
                [4000.0, 40000.0],
                [40000.0],
            ],
            volume_interaction=[
                [
                    -3.0000000000000004e-07,
                    -6.000000000000001e-07,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    -3.0000000000000004e-07,
                    -3.0000000000000004e-07,
                    0.0,
                ],
                [-1.0000000000000002e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0, 0.0, -3.5e-06, -1.0000000000000002e-06, 0.0],
                [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0],
                [0.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class opx_W24(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a opx_W24 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.en(), "[Mgmone][Mgmtwo][Sit]1/2"]
        * [HPx_ds636.fs(), "[Femone][Femtwo][Sit]1/2"]
        * [fm, "[Mgmone][Femtwo][Sit]1/2"]
        * [odi, "[Mgmone][Camtwo][Sit]1/2"]
        * [HPx_ds636.mgts(), "[Almone][Mgmtwo][Sit1/2Alt1/2]1/2"]
        * [cren, "[Crmone][Mgmtwo][Sit1/2Alt1/2]1/2"]
        * [obuf, "[Mgmone1/2Timone1/2][Mgmtwo][Sit1/2Alt1/2]1/2"]
        * [mess, "[Fethreemone][Mgmtwo][Sit1/2Alt1/2]1/2"]
        * [ojd, "[Almone][Namtwo][Sit]1/2"]

        This is implemented as an asymmetric solution.
        """
        self.name = "opx_W24"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.en(), "[Mgmone][Mgmtwo][Sit]1/2"],
                [HPx_ds636.fs(), "[Femone][Femtwo][Sit]1/2"],
                [fm, "[Mgmone][Femtwo][Sit]1/2"],
                [odi, "[Mgmone][Camtwo][Sit]1/2"],
                [HPx_ds636.mgts(), "[Almone][Mgmtwo][Sit1/2Alt1/2]1/2"],
                [cren, "[Crmone][Mgmtwo][Sit1/2Alt1/2]1/2"],
                [obuf, "[Mgmone1/2Timone1/2][Mgmtwo][Sit1/2Alt1/2]1/2"],
                [mess, "[Fethreemone][Mgmtwo][Sit1/2Alt1/2]1/2"],
                [ojd, "[Almone][Namtwo][Sit]1/2"],
            ],
            alphas=[1.0, 1.0, 1.0, 1.2, 1.0, 1.0, 1.0, 1.0, 1.2],
            energy_interaction=[
                [7000.0, 3500.0, 29000.0, 12500.0, 8000.0, 6000.0, 8000.0, 35000.0],
                [4500.0, 23000.0, 11000.0, 10000.0, 7000.0, 10000.0, 35000.0],
                [19000.0, 15000.0, 12000.0, 8000.0, 12000.0, 35000.0],
                [75500.0, 20000.0, 40000.0, 20000.0, 35000.0],
                [2000.0, 10000.0, 2000.0, 7000.0],
                [6000.0, 2000.0, -11000.0],
                [6000.0, 20000.0],
                [-11000.0],
            ],
            volume_interaction=[
                [0.0, 0.0, 1.5e-06, -4.0000000000000003e-07, 0.0, 0.0, 0.0, 0.0],
                [0.0, 8.000000000000001e-07, -1.5e-06, 0.0, 0.0, 0.0, 0.0],
                [8.000000000000001e-07, -1.5e-06, 0.0, 0.0, 0.0, 0.0],
                [-8.400000000000001e-06, 0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0],
                [0.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class ilm_W24(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a ilm_W24 solution object.
        Contains the following endmembers with associated site occupancies:
        * [oilm, "[Fea]1/2[Tib]1/2"]
        * [dilm, "[Fea1/2Tia1/2]1/2[Feb1/2Tib1/2]1/2"]
        * [HPx_ds636.hem(), "[Fethreea]1/2[Fethreeb]1/2"]
        * [ogk, "[Mga]1/2[Tib]1/2"]
        * [dgk, "[Tia1/2Mga1/2]1/2[Tib1/2Mgb1/2]1/2"]

        This is implemented as a symmetric solution.
        """
        self.name = "ilm_W24"
        self.solution_model = SymmetricRegularSolution(
            endmembers=[
                [oilm, "[Fea]1/2[Tib]1/2"],
                [dilm, "[Fea1/2Tia1/2]1/2[Feb1/2Tib1/2]1/2"],
                [HPx_ds636.hem(), "[Fethreea]1/2[Fethreeb]1/2"],
                [ogk, "[Mga]1/2[Tib]1/2"],
                [dgk, "[Tia1/2Mga1/2]1/2[Tib1/2Mgb1/2]1/2"],
            ],
            energy_interaction=[
                [7050.0, 14300.0, -7600.0, 600.0],
                [7250.0, -5500.0, -2200.0],
                [12500.0, 2700.0],
                [8300.0],
            ],
            volume_interaction=[
                [1.3e-06, 0.0, 0.0, 0.0],
                [-1.3e-06, 0.0, 0.0],
                [0.0, 0.0],
                [0.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class bi_G25(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a bi_G25 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.phl(), "[Mgmthree][Mgmonetwo]2[Sit1/2Alt1/2]2[Ohv]2"]
        * [annm, "[Femthree][Femonetwo]2[Sit1/2Alt1/2]2[Ohv]2"]
        * [obi, "[Femthree][Mgmonetwo]2[Sit1/2Alt1/2]2[Ohv]2"]
        * [est, "[Almthree][Mgmonetwo]2[Alt]2[Ohv]2"]
        * [tbi, "[Timthree][Mgmonetwo]2[Sit1/2Alt1/2]2[Ov]2"]
        * [fbi, "[Fethreemthree][Mgmonetwo]2[Alt]2[Ohv]2"]

        This is implemented as a symmetric solution.
        """
        self.name = "bi_G25"
        self.solution_model = SymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.phl(), "[Mgmthree][Mgmonetwo]2[Sit1/2Alt1/2]2[Ohv]2"],
                [annm, "[Femthree][Femonetwo]2[Sit1/2Alt1/2]2[Ohv]2"],
                [obi, "[Femthree][Mgmonetwo]2[Sit1/2Alt1/2]2[Ohv]2"],
                [est, "[Almthree][Mgmonetwo]2[Alt]2[Ohv]2"],
                [tbi, "[Timthree][Mgmonetwo]2[Sit1/2Alt1/2]2[Ov]2"],
                [fbi, "[Fethreemthree][Mgmonetwo]2[Alt]2[Ohv]2"],
            ],
            energy_interaction=[
                [12000.0, 4000.0, 10000.0, 30000.0, 14000.0],
                [8000.0, 0.0, 32000.0, 4000.0],
                [7000.0, 24000.0, 7000.0],
                [40000.0, 1000.0],
                [40000.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class mu_W14(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a mu_W14 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.mu(), "[Ka][Almtwoa][Almtwob][Sitone1/2Altone1/2]2"]
        * [HPx_ds636.cel(), "[Ka][Mgmtwoa][Almtwob][Sitone]2"]
        * [HPx_ds636.fcel(), "[Ka][Femtwoa][Almtwob][Sitone]2"]
        * [HPx_ds636.pa(), "[Naa][Almtwoa][Almtwob][Sitone1/2Altone1/2]2"]
        * [mat, "[Caa][Almtwoa][Almtwob][Altone]2"]
        * [fmu, "[Ka][Almtwoa][Fethreemtwob][Sitone1/2Altone1/2]2"]

        This is implemented as an asymmetric solution.
        """
        self.name = "mu_W14"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.mu(), "[Ka][Almtwoa][Almtwob][Sitone1/2Altone1/2]2"],
                [HPx_ds636.cel(), "[Ka][Mgmtwoa][Almtwob][Sitone]2"],
                [HPx_ds636.fcel(), "[Ka][Femtwoa][Almtwob][Sitone]2"],
                [HPx_ds636.pa(), "[Naa][Almtwoa][Almtwob][Sitone1/2Altone1/2]2"],
                [mat, "[Caa][Almtwoa][Almtwob][Altone]2"],
                [fmu, "[Ka][Almtwoa][Fethreemtwob][Sitone1/2Altone1/2]2"],
            ],
            alphas=[0.63, 0.63, 0.63, 0.37, 0.63, 0.63],
            energy_interaction=[
                [0.0, 0.0, 10120.0, 35000.0, 0.0],
                [0.0, 45000.0, 50000.0, 0.0],
                [45000.0, 50000.0, 0.0],
                [15000.0, 30000.0],
                [35000.0],
            ],
            entropy_interaction=[
                [-0.0, -0.0, -3.4, -0.0, -0.0],
                [-0.0, -0.0, -0.0, -0.0],
                [-0.0, -0.0, -0.0],
                [-0.0, -0.0],
                [-0.0],
            ],
            volume_interaction=[
                [2.0000000000000003e-06, 2.0000000000000003e-06, 3.53e-06, 0.0, 0.0],
                [0.0, 2.5e-06, 0.0, 0.0],
                [2.5e-06, 0.0, 0.0],
                [0.0, 0.0],
                [0.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class amp_G16(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a amp_G16 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.tr(), "[Va][Mgmonethree]3[Mgmtwo]2[Camfour]2[Sitone][Ohv]2"]
        * [tsm, "[Va][Mgmonethree]3[Almtwo]2[Camfour]2[Sitone1/2Altone1/2][Ohv]2"]
        * [prgm, "[Naa][Mgmonethree]3[Mgmtwo1/2Almtwo1/2]2[Camfour]2[Sitone1/2Altone1/2][Ohv]2"]
        * [glm, "[Va][Mgmonethree]3[Almtwo]2[Namfour]2[Sitone][Ohv]2"]
        * [HPx_ds636.cumm(), "[Va][Mgmonethree]3[Mgmtwo]2[Mgmfour]2[Sitone][Ohv]2"]
        * [grnm, "[Va][Femonethree]3[Femtwo]2[Femfour]2[Sitone][Ohv]2"]
        * [a, "[Va][Mgmonethree]3[Femtwo]2[Femfour]2[Sitone][Ohv]2"]
        * [b, "[Va][Femonethree]3[Mgmtwo]2[Femfour]2[Sitone][Ohv]2"]
        * [mrb, "[Va][Mgmonethree]3[Fethreemtwo]2[Namfour]2[Sitone][Ohv]2"]
        * [kprg, "[Ka][Mgmonethree]3[Mgmtwo1/2Almtwo1/2]2[Camfour]2[Sitone1/2Altone1/2][Ohv]2"]
        * [tts, "[Va][Mgmonethree]3[Timtwo]2[Camfour]2[Sitone1/2Altone1/2][Ov]2"]

        This is implemented as an asymmetric solution.
        """
        self.name = "amp_G16"
        self.solution_model = AsymmetricRegularSolution(
            endmembers=[
                [
                    HPx_ds636.tr(),
                    "[Va][Mgmonethree]3[Mgmtwo]2[Camfour]2[Sitone][Ohv]2",
                ],
                [
                    tsm,
                    "[Va][Mgmonethree]3[Almtwo]2[Camfour]2[Sitone1/2Altone1/2][Ohv]2",
                ],
                [
                    prgm,
                    "[Naa][Mgmonethree]3[Mgmtwo1/2Almtwo1/2]2[Camfour]2[Sitone1/2Altone1/2][Ohv]2",
                ],
                [glm, "[Va][Mgmonethree]3[Almtwo]2[Namfour]2[Sitone][Ohv]2"],
                [
                    HPx_ds636.cumm(),
                    "[Va][Mgmonethree]3[Mgmtwo]2[Mgmfour]2[Sitone][Ohv]2",
                ],
                [grnm, "[Va][Femonethree]3[Femtwo]2[Femfour]2[Sitone][Ohv]2"],
                [a, "[Va][Mgmonethree]3[Femtwo]2[Femfour]2[Sitone][Ohv]2"],
                [b, "[Va][Femonethree]3[Mgmtwo]2[Femfour]2[Sitone][Ohv]2"],
                [mrb, "[Va][Mgmonethree]3[Fethreemtwo]2[Namfour]2[Sitone][Ohv]2"],
                [
                    kprg,
                    "[Ka][Mgmonethree]3[Mgmtwo1/2Almtwo1/2]2[Camfour]2[Sitone1/2Altone1/2][Ohv]2",
                ],
                [tts, "[Va][Mgmonethree]3[Timtwo]2[Camfour]2[Sitone1/2Altone1/2][Ov]2"],
            ],
            alphas=[1.0, 1.5, 1.7, 0.8, 1.0, 1.0, 1.0, 1.0, 0.8, 1.7, 1.5],
            energy_interaction=[
                [
                    20000.0,
                    25000.0,
                    65000.0,
                    45000.0,
                    75000.0,
                    57000.0,
                    63000.0,
                    52000.0,
                    30000.0,
                    85000.0,
                ],
                [
                    -40000.0,
                    25000.0,
                    70000.0,
                    80000.0,
                    70000.0,
                    72500.0,
                    20000.0,
                    -40000.0,
                    35000.0,
                ],
                [
                    50000.0,
                    90000.0,
                    106700.0,
                    94800.0,
                    94800.0,
                    40000.0,
                    8000.0,
                    15000.0,
                ],
                [100000.0, 113500.0, 100000.0, 111200.0, 0.0, 54000.0, 75000.0],
                [33000.0, 18000.0, 23000.0, 80000.0, 87000.0, 100000.0],
                [12000.0, 8000.0, 91000.0, 96000.0, 65000.0],
                [20000.0, 80000.0, 94000.0, 95000.0],
                [90000.0, 94000.0, 95000.0],
                [50000.0, 50000.0],
                [35000.0],
            ],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class ep_H11(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a ep_H11 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.cz(), "[Almone][Almthree]"]
        * [HPx_ds636.ep(), "[Almone][Femthree]"]
        * [HPx_ds636.fep(), "[Femone][Femthree]"]

        This is implemented as a symmetric solution.
        """
        self.name = "ep_H11"
        self.solution_model = SymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.cz(), "[Almone][Almthree]"],
                [HPx_ds636.ep(), "[Almone][Femthree]"],
                [HPx_ds636.fep(), "[Femone][Femthree]"],
            ],
            energy_interaction=[[1000.0, 3000.0], [1000.0]],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)


class cd_G25(Solution):
    def __init__(self, molar_fractions=None):
        """
        Initialisation for a cd_G25 solution object.
        Contains the following endmembers with associated site occupancies:
        * [HPx_ds636.crd(), "[Mgx]2[Vh]"]
        * [HPx_ds636.fcrd(), "[Fex]2[Vh]"]
        * [HPx_ds636.hcrd(), "[Mgx]2[Htwooh]"]

        This is implemented as a symmetric solution.
        """
        self.name = "cd_G25"
        self.solution_model = SymmetricRegularSolution(
            endmembers=[
                [HPx_ds636.crd(), "[Mgx]2[Vh]"],
                [HPx_ds636.fcrd(), "[Fex]2[Vh]"],
                [HPx_ds636.hcrd(), "[Mgx]2[Htwooh]"],
            ],
            energy_interaction=[[2500.0, 0.0], [2000.0]],
        )
        Solution.__init__(self, molar_fractions=molar_fractions)
